services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_php
        volumes:
            - .:/var/www/html
        networks:
            - symfony

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

        depends_on:
            - php
        networks:
            - symfony

    database:
        image: postgres:16-alpine
        container_name: symfony_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - symfony

networks:
    symfony:
        driver: bridge

volumes:
    postgres_data:
